apiVersion : apps/v1
kind: Deployment
metadata:
  name: "moatazkubernetesdemo-6f2b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "moatazkubernetesdemo-6f2b"
  template:
    metadata:
      labels:
        app: "moatazkubernetesdemo-6f2b"
    spec:
      containers:
        - name: "moatazkubernetesdemo-6f2b"
          image: "moatazregistrynamedemo.azurecr.io/moatazkubernetesdemo"
          ports:
          - containerPort: 80