on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: moatazregistrynamedemo.azurecr.io
        username: ${{ secrets.acr_moatazregistrynamedemo_username }}
        password: ${{ secrets.acr_moatazregistrynamedemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t moatazregistrynamedemo.azurecr.io/moatazkubernetesdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push moatazregistrynamedemo.azurecr.io/moatazkubernetesdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_moatazkubernetesdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep moatazkubernetesdemo9863 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace moatazkubernetesdemo9863`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: moatazkubernetesdemo9863
        container-registry-url: moatazregistrynamedemo.azurecr.io
        container-registry-username: ${{ secrets.acr_moatazregistrynamedemo_username }}
        container-registry-password: ${{ secrets.acr_moatazregistrynamedemo_password }}
        secret-name: moatazkuberndockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: moatazkubernetesdemo9863
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          moatazregistrynamedemo.azurecr.io/moatazkubernetesdemo:${{ github.sha }}
        imagepullsecrets: |
          moatazkuberndockerauth
